In [75]:
np.random.seed(42)          # fix results
print(np.random.rand(4))    # [0.374540, 0.950714, 0.731994]
print(np.random.randn(3))   # normal distribution
print(np.random.randint(1, 10, 5))  # 5 integers from 1–9


[0.37454012 0.95071431 0.73199394 0.59865848]
[-0.23415337 -0.23413696  1.57921282]
[6 5 2 8 6]


In [54]:
import numpy as np
arr = np.arange(1,101)

a=arr[arr>50]
arr[arr<20]=0
print(a)
print(arr)



[ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100]
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [63]:
import numpy as np
a= np.random.randint(1,10,(3,3))
b= np.random.randint(1,10,(3,3))
print(a)
print(a.T)
print(b)
print(np.dot(a,b))

[[5 8 8]
 [6 1 9]
 [9 6 5]]
[[5 6 9]
 [8 1 6]
 [8 9 5]]
[[6 5 3]
 [4 3 3]
 [3 9 7]]
[[ 86 121  95]
 [ 67 114  84]
 [ 93 108  80]]
